# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CrashTheRobot.com
email: 
description: > # this means to ignore newlines until "baseurl:"
 CrashTheRobot.com explores possible solutions to today's safety and security problems in robotics, AI, drones and related fields. Also, we crash robots. 

baseurl: "" # the subpath of your site, e.g. /blog
imgurl: ""
url: "http://crashtherobot.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  crashtherobotsite

# Build settings
markdown: kramdown
exclude: [vendor]

#https://github.com/jekyll/jekyll-sitemap
#Plugin to build Google- search engine happy sitemap. 
#Note from install site:
#If all gem plugins have the same priority, they will be executed in the order they are required, generally.
# Thus, if you have other plugins which generate content and store that content in site.pages, site.posts,
# or site.collections, be sure to require jekyll-sitemap either after those other gems if you want the
# sitemap to include the generated content, or before those other gems if you don't want the sitemap to
# include the generated content from the gems.  
gems:
  - jekyll-sitemap


# Google services
google_analytics: UA-81200964-1
