# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CrashTheRobot.com
email: 
description: > # this means to ignore newlines until "baseurl:"
 The CrashTheRobot.com blog explores and explains today's safety-and-security-related problems and solutions in robotics, AI, drones and other related fields. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://crashtherobot.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  crashtherobotsite

# Build settings
markdown: kramdown
